CREATE TABLE IF NOT EXISTS events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date       DATE NOT NULL,
  description VARCHAR(200),
  end_time   TIME(6) NOT NULL,
  name       VARCHAR(20) NOT NULL,
  start_time TIME(6) NOT NULL,
  owner_id   BIGINT,
  PRIMARY KEY (id)
);