CREATE TABLE IF NOT EXISTS group_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(30) NOT NULL,
    description VARCHAR(200),
    date       DATE,
    start_time TIME(6),
    end_time   TIME(6),
    status     VARCHAR(255) CHECK (status IN ('PENDING','CONFIRMED')),
    owner_id   BIGINT,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS group_event_participants (
    group_event_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    PRIMARY KEY (group_event_id, participant_id),
    FOREIGN KEY (group_event_id) REFERENCES group_events(id)
    );
